

clear @a[tag=!SX,hasitem={item=chicken_spawn_egg}] chicken_spawn_egg
clear @a[tag=!SX,hasitem={item=bee_spawn_egg}] bee_spawn_egg
clear @a[tag=!SX,hasitem={item=cod_spawn_egg}] cod_spawn_egg
clear @a[tag=!SX,hasitem={item=cow_spawn_egg}] cow_spawn_egg
clear @a[tag=!SX,hasitem={item=pig_spawn_egg}] pig_spawn_egg
clear @a[tag=!SX,hasitem={item=sheep_spawn_egg}] sheep_spawn_egg
clear @a[tag=!SX,hasitem={item=wolf_spawn_egg}] wolf_spawn_egg
clear @a[tag=!SX,hasitem={item=polar_bear_spawn_egg}] polar_bear_spawn_egg
clear @a[tag=!SX,hasitem={item=ocelot_spawn_egg}] ocelot_spawn_egg
clear @a[tag=!SX,hasitem={item=cat_spawn_egg}] cat_spawn_egg
clear @a[tag=!SX,hasitem={item=mooshroom_spawn_egg}] mooshroom_spawn_egg
clear @a[tag=!SX,hasitem={item=fox_spawn_egg}] fox_spawn_egg
clear @a[tag=!SX,hasitem={item=bat_spawn_egg}] bat_spawn_egg
clear @a[tag=!SX,hasitem={item=axolotl_spawn_egg}] axolotl_spawn_egg
clear @a[tag=!SX,hasitem={item=salmon_spawn_egg}] salmon_spawn_egg
clear @a[tag=!SX,hasitem={item=pufferfish_spawn_egg}] pufferfish_spawn_egg
clear @a[tag=!SX,hasitem={item=tropical_fish_spawn_egg}] tropical_fish_spawn_egg
clear @a[tag=!SX,hasitem={item=dolphin_spawn_egg}] dolphin_spawn_egg
clear @a[tag=!SX,hasitem={item=turtle_spawn_egg}] turtle_spawn_egg
clear @a[tag=!SX,hasitem={item=spider_spawn_egg}] spider_spawn_egg
clear @a[tag=!SX,hasitem={item=cave_spider_spawn_egg}] cave_spider_spawn_egg
clear @a[tag=!SX,hasitem={item=zombie_spawn_egg}] zombie_spawn_egg
clear @a[tag=!SX,hasitem={item=skeleton_spawn_egg}] skeleton_spawn_egg
clear @a[tag=!SX,hasitem={item=creeper_spawn_egg}] creeper_spawn_egg
clear @a[tag=!SX,hasitem={item=enderman_spawn_egg}] enderman_spawn_egg
clear @a[tag=!SX,hasitem={item=blaze_spawn_egg}] blaze_spawn_egg
clear @a[tag=!SX,hasitem={item=slime_spawn_egg}] slime_spawn_egg
clear @a[tag=!SX,hasitem={item=magma_cube_spawn_egg}] magma_cube_spawn_egg
clear @a[tag=!SX,hasitem={item=ghast_spawn_egg}] ghast_spawn_egg
clear @a[tag=!SX,hasitem={item=guardian_spawn_egg}] guardian_spawn_egg
clear @a[tag=!SX,hasitem={item=elder_guardian_spawn_egg}] elder_guardian_spawn_egg
clear @a[tag=!SX,hasitem={item=shulker_spawn_egg}] shulker_spawn_egg
clear @a[tag=!SX,hasitem={item=silverfish_spawn_egg}] silverfish_spawn_egg
clear @a[tag=!SX,hasitem={item=pillager_spawn_egg}] pillager_spawn_egg
clear @a[tag=!SX,hasitem={item=vex_spawn_egg}] vex_spawn_egg
clear @a[tag=!SX,hasitem={item=phantom_spawn_egg}] phantom_spawn_egg
clear @a[tag=!SX,hasitem={item=rabbit_spawn_egg}] rabbit_spawn_egg
clear @a[tag=!SX,hasitem={item=panda_spawn_egg}] panda_spawn_egg
clear @a[tag=!SX,hasitem={item=trader_llama_spawn_egg}] trader_llama_spawn_egg
clear @a[tag=!SX,hasitem={item=llama_spawn_egg}] llama_spawn_egg
clear @a[tag=!SX,hasitem={item=donkey_spawn_egg}] donkey_spawn_egg
clear @a[tag=!SX,hasitem={item=mule_spawn_egg}] mule_spawn_egg
clear @a[tag=!SX,hasitem={item=horse_spawn_egg}] horse_spawn_egg
clear @a[tag=!SX,hasitem={item=villager_spawn_egg}] villager_spawn_egg
clear @a[tag=!SX,hasitem={item=parrot_spawn_egg}] parrot_spawn_egg
clear @a[tag=!SX,hasitem={item=skeleton_horse_spawn_egg}] skeleton_horse_spawn_egg
clear @a[tag=!SX,hasitem={item=zombie_horse_spawn_egg}] zombie_horse_spawn_egg
clear @a[tag=!SX,hasitem={item=wither_skeleton_spawn_egg}] wither_skeleton_spawn_egg
clear @a[tag=!SX,hasitem={item=stray_spawn_egg}] stray_spawn_egg
clear @a[tag=!SX,hasitem={item=zombie_pigman_spawn_egg}] zombie_pigman_spawn_egg
clear @a[tag=!SX,hasitem={item=husk_spawn_egg}] husk_spawn_egg
clear @a[tag=!SX,hasitem={item=drowned_spawn_egg}] drowned_spawn_egg
clear @a[tag=!SX,hasitem={item=squid_spawn_egg}] squid_spawn_egg
clear @a[tag=!SX,hasitem={item=endermite_spawn_egg}] endermite_spawn_egg
clear @a[tag=!SX,hasitem={item=strider_spawn_egg}] strider_spawn_egg
clear @a[tag=!SX,hasitem={item=hoglin_spawn_egg}] hoglin_spawn_egg
clear @a[tag=!SX,hasitem={item=piglin_spawn_egg}] piglin_spawn_egg
clear @a[tag=!SX,hasitem={item=zoglin_spawn_egg}] zoglin_spawn_egg
clear @a[tag=!SX,hasitem={item=piglin_brute_spawn_egg}] piglin_brute_spawn_egg
clear @a[tag=!SX,hasitem={item=goat_spawn_egg}] goat_spawn_egg
clear @a[tag=!SX,hasitem={item=glow_squid_spawn_egg}] glow_squid_spawn_egg
clear @a[tag=!SX,hasitem={item=witch_spawn_egg}] witch_spawn_egg
clear @a[tag=!SX,hasitem={item=warden_spawn_egg}] warden_spawn_egg
clear @a[tag=!SX,hasitem={item=allay_spawn_egg}] allay_spawn_egg
clear @a[tag=!SX,hasitem={item=frog_spawn_egg}] frog_spawn_egg
clear @a[tag=!SX,hasitem={item=tadpole_spawn_egg}] tadpole_spawn_egg
clear @a[tag=!SX,hasitem={item=camel_spawn_egg}] camel_spawn_egg
clear @a[tag=!SX,hasitem={item=vindicator_spawn_egg}] vindicator_spawn_egg
clear @a[tag=!SX,hasitem={item=evoker_spawn_egg}] evoker_spawn_egg
clear @a[tag=!SX,hasitem={item=wandering_trader_spawn_egg}] wandering_trader_spawn_egg
clear @a[tag=!SX,hasitem={item=zombie_villager_spawn_egg}] zombie_villager_spawn_egg
clear @a[tag=!SX,hasitem={item=ravager_spawn_egg}] ravager_spawn_egg
clear @a[tag=!SX,hasitem={item=iron_golem_spawn_egg}] iron_golem_spawn_egg
clear @a[tag=!SX,hasitem={item=snow_golem_spawn_egg}] snow_golem_spawn_egg
clear @a[tag=!SX,hasitem={item=sniffer_spawn_egg}] sniffer_spawn_egg
clear @a[tag=!SX,hasitem={item=breeze_spawn_egg}] breeze_spawn_egg
clear @a[tag=!SX,hasitem={item=armadillo_spawn_egg}] armadillo_spawn_egg
clear @a[tag=!SX,hasitem={item=bogged_spawn_egg}] bogged_spawn_egg
clear @a[tag=!SX,hasitem={item=creaking_spawn_egg}] creaking_spawn_egg
clear @a[tag=!SX,hasitem={item=happy_ghast_spawn_egg}] happy_ghast_spawn_egg

clear @a[tag=!SX,hasitem={item=oak_boat}] oak_boat
clear @a[tag=!SX,hasitem={item=spruce_boat}] spruce_boat
clear @a[tag=!SX,hasitem={item=birch_boat}] birch_boat
clear @a[tag=!SX,hasitem={item=jungle_boat}] jungle_boat
clear @a[tag=!SX,hasitem={item=acacia_boat}] acacia_boat
clear @a[tag=!SX,hasitem={item=dark_oak_boat}] dark_oak_boat
clear @a[tag=!SX,hasitem={item=oak_chest_boat}] oak_chest_boat
clear @a[tag=!SX,hasitem={item=spruce_chest_boat}] spruce_chest_boat
clear @a[tag=!SX,hasitem={item=birch_chest_boat}] birch_chest_boat
clear @a[tag=!SX,hasitem={item=jungle_chest_boat}] jungle_chest_boat
clear @a[tag=!SX,hasitem={item=acacia_chest_boat}] acacia_chest_boat
clear @a[tag=!SX,hasitem={item=dark_oak_chest_boat}] dark_oak_chest_boat
clear @a[tag=!SX,hasitem={item=mangrove_boat}] mangrove_boat
clear @a[tag=!SX,hasitem={item=cherry_boat}] cherry_boat
clear @a[tag=!SX,hasitem={item=pale_oak_boat}] pale_oak_boat
clear @a[tag=!SX,hasitem={item=bamboo_raft}] bamboo_raft
clear @a[tag=!SX,hasitem={item=mangrove_chest_boat}] mangrove_chest_boat
clear @a[tag=!SX,hasitem={item=cherry_chest_boat}] cherry_chest_boat
clear @a[tag=!SX,hasitem={item=pale_oak_chest_boat}] pale_oak_chest_boat
clear @a[tag=!SX,hasitem={item=bamboo_chest_raft}] bamboo_chest_raft

clear @a[tag=!SX,hasitem={item=crafting_table}] crafting_table
clear @a[tag=!SX,hasitem={item=enchanting_table}] enchanting_table
clear @a[tag=!SX,hasitem={item=smithing_table}] smithing_table
clear @a[tag=!SX,hasitem={item=grindstone}] grindstone
clear @a[tag=!SX,hasitem={item=barrel}] barrel
clear @a[tag=!SX,hasitem={item=smoker}] smoker
clear @a[tag=!SX,hasitem={item=blast_furnace}] blast_furnace
clear @a[tag=!SX,hasitem={item=furnace}] furnace
clear @a[tag=!SX,hasitem={item=piston}] piston
clear @a[tag=!SX,hasitem={item=sticky_piston}] sticky_piston

clear @a[tag=!SX,hasitem={item=wooden_hoe}] wooden_hoe
clear @a[tag=!SX,hasitem={item=stone_hoe}] stone_hoe
clear @a[tag=!SX,hasitem={item=iron_hoe}] iron_hoe
clear @a[tag=!SX,hasitem={item=golden_hoe}] golden_hoe
clear @a[tag=!SX,hasitem={item=diamond_hoe}] diamond_hoe
clear @a[tag=!SX,hasitem={item=netherite_hoe}] netherite_hoe
clear @a[tag=!SX,hasitem={item=wooden_shovel}] wooden_shovel
clear @a[tag=!SX,hasitem={item=stone_shovel}] stone_shovel
clear @a[tag=!SX,hasitem={item=iron_shovel}] iron_shovel
clear @a[tag=!SX,hasitem={item=golden_shovel}] golden_shovel
clear @a[tag=!SX,hasitem={item=diamond_shovel}] diamond_shovel
clear @a[tag=!SX,hasitem={item=netherite_shovel}] netherite_shovel
clear @a[tag=!SX,hasitem={item=flint_and_steel}] flint_and_steel

clear @a[tag=!SX,hasitem={item=bundle}] bundle
clear @a[tag=!SX,hasitem={item=white_bundle}] white_bundle
clear @a[tag=!SX,hasitem={item=orange_bundle}] orange_bundle
clear @a[tag=!SX,hasitem={item=magenta_bundle}] magenta_bundle
clear @a[tag=!SX,hasitem={item=light_blue_bundle}] light_blue_bundle
clear @a[tag=!SX,hasitem={item=yellow_bundle}] yellow_bundle
clear @a[tag=!SX,hasitem={item=lime_bundle}] lime_bundle
clear @a[tag=!SX,hasitem={item=pink_bundle}] pink_bundle
clear @a[tag=!SX,hasitem={item=gray_bundle}] gray_bundle
clear @a[tag=!SX,hasitem={item=light_gray_bundle}] light_gray_bundle
clear @a[tag=!SX,hasitem={item=cyan_bundle}] cyan_bundle
clear @a[tag=!SX,hasitem={item=purple_bundle}] purple_bundle
clear @a[tag=!SX,hasitem={item=blue_bundle}] blue_bundle
clear @a[tag=!SX,hasitem={item=brown_bundle}] brown_bundle
clear @a[tag=!SX,hasitem={item=green_bundle}] green_bundle
clear @a[tag=!SX,hasitem={item=red_bundle}] red_bundle
clear @a[tag=!SX,hasitem={item=black_bundle}] black_bundle
clear @a[tag=!SX,hasitem={item=dried_ghast}] dried_ghast 
clear @a[tag=!SX,hasitem={item=painting}] painting
clear @a[tag=!SX,hasitem={item=frame}] frame
clear @a[tag=!SX,hasitem={item=glow_frame}] glow_frame
clear @a[tag=!SX,hasitem={item=minecart}] minecart
clear @a[tag=!SX,hasitem={item=brown_egg}] brown_egg
clear @a[tag=!SX,hasitem={item=blue_egg}] blue_egg
clear @a[tag=!SX,hasitem={item=lead}] lead
clear @a[tag=!SX,hasitem={item=structure_void}] structure_void
clear @a[tag=!SX,hasitem={item=bed}] bed
clear @a[tag=!SX,hasitem={item=empty_map}] empty_map
clear @a[tag=!SX,hasitem={item=armor_stand}] armor_stand
clear @a[tag=!SX,hasitem={item=lava_bucket}] lava_bucket
clear @a[tag=!SX,hasitem={item=bucket}] bucket
clear @a[tag=!SX,hasitem={item=water_bucket}] water_bucket
clear @a[tag=!SX,hasitem={item=respawn_anchor}] respawn_anchor
clear @a[tag=!SX,hasitem={item=chest}] chest
